# Generated by Django 4.2.3 on 2023-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_karaokesong_song_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaokesong',
            name='photo',
            field=models.ImageField(null=True, upload_to='music-photos/'),
        ),
    ]
