# Generated by Django 4.2.3 on 2023-08-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_karaokesong_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karaokesong',
            old_name='photo',
            new_name='image',
        ),
    ]
