# Generated by Django 4.2.3 on 2023-07-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('video_code', models.CharField(default='', max_length=8)),
                ('description', models.TextField()),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_videos', to='api.course')),
            ],
        ),
    ]
