# Generated by Django 4.2.3 on 2023-07-29 17:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_video_thumbnail_alter_course_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_code',
            field=models.CharField(default=api.models.generate_unique_video_code, max_length=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(default=api.models.generate_unique_course_number),
        ),
    ]
